version: "3"
services:
  sportstore:
    build: .
    ports:
    - "5000:5000"
    environment:
    - ASPNECTORE_INVIRONMENT=Production
    depends_on:
    - npgsql
  npgsql:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=3141592
    ports:
    - "5451:5432"